name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # 1. 리포지토리 클론
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Node.js 환경 설정
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3. 종속성 설치 및 빌드
    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    # 4. SSH를 통해 EC2로 파일 전송
    - name: Deploy to EC2
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: |
          .next
          node_modules
          public
          package.json
          package-lock.json
        target: '/var/www/next-ec2-deploy'
        strip_components: 0

    # 5. SSH로 애플리케이션 실행
    - name: Start Application
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/next-ec2-deploy
          npm install
          pm2 restart next-app || pm2 start npm --name "next-app" -- start